"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-3=7h=+mugk_!%7%5d^73egv0gf+(0#i+i1lps^m*^=5%*+dz4y"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    # Django 核心
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",  # allauth 依赖
    'django.contrib.postgres',
    
    # 第三方基础插件
    "corsheaders",
    "rest_framework",
    "django_filters",
    
    # 认证体系 (allauth)
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # 如果以后要接入 GitHub/Google 登录，在这里加 provider
    
    # 自定义 App (建议先 accounts 后 knowledge，体现依赖关系)
    "accounts.apps.AccountConfig",  # 确保文件夹名是 accounts
    "knowledge.apps.KnowledgeConfig",
]

# 必须配套的设置
AUTH_USER_MODEL = 'accounts.User'
SITE_ID = 1

# --- 新配置 (推荐) ---
# 1. 登录方式：支持用户名或邮箱登录
ACCOUNT_LOGIN_METHODS = {'username', 'email'}

# 2. 注册字段：星号 (*) 表示必填
# 包含 email, username, password1 (确认密码通常在前端处理，或在此添加 password2)
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*']

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # 放在最上面
    "allauth.account.middleware.AccountMiddleware",  # 处理用户认证
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOW_ALL_ORIGINS = True  # 开发环境

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "ai_kms_db",
        "USER": "ai_admin",
        "PASSWORD": "123",
        "HOST": "127.0.0.1",  # 这里的 127.0.0.1 指向你 Mac 的端口，由 Docker 转发给容器
        "PORT": "5432",
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
# 开发环境下禁用严格密码校验
if DEBUG:
    AUTH_PASSWORD_VALIDATORS = []
else:
    AUTH_PASSWORD_VALIDATORS = [
        {
            "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
        },
    ]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
