# Generated by Django 6.0.3 on 2026-04-03 03:46

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'knowledge_bases',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file_path', models.TextField()),
                ('is_public', models.BooleanField(default=False)),
                ('tags', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_kb_links', to='knowledge.document')),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kb_document_links', to='knowledge.knowledgebase')),
            ],
            options={
                'db_table': 'knowledge_base_documents',
                'unique_together': {('knowledge_base', 'document')},
            },
        ),
        migrations.AddField(
            model_name='document',
            name='knowledge_bases',
            field=models.ManyToManyField(related_name='documents', through='knowledge.KnowledgeBaseDocument', to='knowledge.knowledgebase'),
        ),
        migrations.CreateModel(
            name='RoleKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kb_role_links', to='knowledge.knowledgebase')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_kb_links', to='accounts.role')),
            ],
            options={
                'db_table': 'role_knowledge_bases',
            },
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='roles',
            field=models.ManyToManyField(related_name='knowledge_bases', through='knowledge.RoleKnowledgeBase', to='accounts.role'),
        ),
        migrations.CreateModel(
            name='DocumentEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('content_chunk', models.TextField()),
                ('chunk_index', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='knowledge.document')),
            ],
            options={
                'db_table': 'document_embeddings',
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='idx_doc_vector', opclasses=['vector_cosine_ops'])],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner'], name='idx_docs_owner'),
        ),
        migrations.AlterUniqueTogether(
            name='roleknowledgebase',
            unique_together={('role', 'knowledge_base')},
        ),
    ]
