# Generated by Django 6.0.3 on 2026-04-03 13:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_path',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='docs/%Y/%m/%d/', verbose_name='物理文件'),
        ),
        migrations.AddField(
            model_name='knowledgebasedocument',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledgebasedocument',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
